// UI
export const SET_LOADING = 'SET_LOADING';

// AUTH
export const AUTH = 'AUTH';
export const SIGNOUT = 'SIGNOUT';

// FRIENDSHIPS
export const SAVE_FRIENDSHIPS = 'SAVE_FRIENDSHIPS';
export const REMOVE_FRIENDSHIP = 'REMOVE_FRIENDSHIP';
export const SAVE_SENT_FRIEND_REQUESTS = 'SAVE_SENT_FRIEND_REQUESTS';
export const REMOVE_SENT_FRIEND_REQUEST = 'REMOVE_SENT_FRIEND_REQUEST';
export const SAVE_RECEIVED_FRIEND_REQUESTS = 'SAVE_RECEIVED_FRIEND_REQUESTS';
export const ACCEPT_RECEIVED_FRIEND_REQUEST = 'ACCEPT_RECEIVED_FRIEND_REQUEST';
export const REMOVE_RECEIVED_FRIEND_REQUEST = 'REMOVE_RECEIVED_FRIEND_REQUEST';
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';

// GAMES
export const SAVE_GAMES = 'GET_GAME_SUCCESS';
export const SAVE_PREVIOUS_GAMES = 'SAVE_PREVIOUS_GAMES';
export const SAVE_SENT_GAME_INVITES = 'SAVE_SENT_GAME_INVITES';
export const SAVE_RECEIVED_GAME_INVITES = 'SAVE_RECEIVED_GAME_INVITES';
export const ACCEPT_GAME_INVITE = 'ACCEPT_GAME_INVITE';
export const SEND_GAME_INVITE = 'SEND_GAME_INVITE';
